# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  TerraformConfigPath: 'terraform'

stages:
  - stage: Initialize
    jobs:
      - job: SourceAction
        steps:
          - checkout: self
            clean: true
            path: s/MyAppSourceArtifact
          - script: echo "Source code has been checked out."
            displayName: 'Check out source code'

  - stage: ApplyTerraform
    dependsOn: Initialize
    jobs:
      - job: ApplyTerraform
        steps:
          - script: |
              az login --identity
              cd $(TerraformConfigPath)
              terraform init
            displayName: 'Apply Terraform Configuration'
