# Terraform Cleanup Pipeline
trigger: none  # Disable automatic triggers

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: secureline-secrets
- name: TerraformConfigPath
  value: 'terraform'

stages:
  - stage: Initialize
    jobs:
      - job: SourceAction
        steps:
          - checkout: self
            clean: true
            path: s/MyAppSourceArtifact
          - script: echo "Source code has been checked out."
            displayName: 'Check out source code'

  - stage: DestroyTerraform
    dependsOn: Initialize
    jobs:
      - job: DestroyTerraform
        steps:
          - script: |
              az login --service-principal -u $(clientid) -p $(clientsecret) --tenant $(tenantid)
              az account set --subscription $(subscriptionid)
              cd $(TerraformConfigPath)
              terraform init
              terraform destroy -auto-approve
            displayName: 'Destroy Terraform Resources'
  