image:
  repository: sonarqube
  tag: 10.6-community
  pullPolicy: IfNotPresent
  
# Security context for the SonarQube container
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Deployment configuration
deployment:
  annotations: {}
  replicas: 1
  updateStrategy:
    type: RollingUpdate

service:
  type: NodePort
  externalPort: 9000
  internalPort: 9000
  nodePort: 30000
  labels:
  annotations: {}
# Ingress configuration (uncomment and modify if needed)
ingress:
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  # hosts:
  #   - name: sonarqube.your-domain.com
  #     path: /
  # tls:
  #   - secretName: sonarqube-tls
  #     hosts:
  #       - sonarqube.your-domain.com

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  
# Database configuration - By default, an embedded H2 database is used
# For production, it's recommended to use an external PostgreSQL
postgresql:
  enabled: true
  postgresqlUsername: $postgresqlUsername
  postgresqlPassword: $postgresqlPassword
  postgresqlDatabase: $postgresqlDatabase
  # Specify the TCP port that PostgreSQL s
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

# External database configuration (if you want to use your own)
# database:
#   type: postgresql
#   host: "postgresql.database.svc.cluster.local"
#   port: 5432
#   user: sonarUser
#   password: sonarPass
#   name: sonarDB

# Resource limits and requests
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Plugins to install
plugins:
  install:
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.14.0/sonarqube-community-branch-plugin-1.14.0.jar"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# JVM options for SonarQube
jvmOpts: "-Xmx2G -Xms1G"

# Additional environment variables
env:
  - name: SONAR_JDBC_USERNAME
    value: sonarqube
  - name: SONAR_JDBC_PASSWORD
    value: sonarqube
  - name: SONAR_JDBC_URL
    value: "jdbc:postgresql://sonarqube-postgresql:5432/sonarqube"
  # Custom admin password configuration
  - name: SONAR_SECURITY_ADMINPASSWORD
    value: $sonarqubepassword  # Replace with your secure password

# nodeSelector, affinity and tolerations for pod assignment
nodeSelector: {}
affinity: {}
tolerations: []

# Readiness and liveness probes
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6